apiVersion: v1
kind: Namespace
metadata:
  name: gotify

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gotify
    app.kubernetes.io/instance: gotify
  name: gotify
  namespace: gotify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotify
  template:
    metadata:
      labels:
        app: gotify
    spec:
      containers:
        - name: gotify
          image: ghcr.io/gotify/server # Replace with desired image tag
          ports:
            - containerPort: 80 # Gotify's default port
          volumeMounts:
            - mountPath: /app/data
              name: gotify-data
      volumes:
        - name: gotify-data
          persistentVolumeClaim:
            claimName: gotify-data

---
apiVersion: v1
kind: Service
metadata:
  name: gotify
  namespace: gotify
spec:
  selector:
    app: gotify
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # Or NodePort, depending on your cluster setup

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gotify
  namespace: gotify
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.gotify.cybertronlabs.us`)
      kind: Rule
      services:
        - name: gotify
          port: 80
    - match: Host(`gotify.cybertronlabs.us`)
      kind: Rule
      services:
        - name: gotify
          port: 80
      middlewares:
        - name: default-headers
          namespace: traefik
        - name: rate-limit
          namespace: traefik
#  tls:
#    secretName: cybertronlabs-tls # change to your cert name
