authentik:
  secret_key: "MCzq8QPQ0kC18wp6mI1jdn2MaiplWbc/OV2TCHVY/tMSoWOGbt3D84scm/KsWgZuqnz4W55nEvI9vsFS"
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
    enabled: false
  postgresql:
    password: "3d8dFzJE9xzBqVN87cEOo9p8fRJn9C14T3ANulydUfZJxn7PXd"

server:
  ingress:
    # Specify kubernetes ingress controller class name
    ingressClassName: traefik
    enabled: true
    hosts:
      - auth.cybertronlabs.us

postgresql:
  enabled: true
  auth:
    password: "3d8dFzJE9xzBqVN87cEOo9p8fRJn9C14T3ANulydUfZJxn7PXd"

redis:
  enabled: true
