apiVersion: v1
kind: Namespace
metadata:
  name: jellyseerr

---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: jellyseerr
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
spec:
  type: ExternalName
  externalName: 192.168.40.9
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseerr
  namespace: jellyseerr
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.jellyseerr.cybertronlabs.us`) # change to your domain
      kind: Rule
      services:
        - name: jellyseerr
          port: 5055
    - match: Host(`jellyseerr.cybertronlabs.us`) # change to your domain
      kind: Rule
      services:
        - name: jellyseerr
          port: 5055
      middlewares:
        - name: bouncer
          namespace: traefik
        #       - name: authentik-outpost
        - name: default-headers
          namespace: traefik
        - name: rate-limit
          namespace: traefik
#  tls:
#    secretName: cybertronlabs-tls # change to your cert name
