config:
  configFile: |
    provider = "github"
    scope = "user:email read:org"
    email_domains = [ "*" ]  # Replace with [ "example.com" ] to limit access to users with specific email domain
    cookie_domains = [ "cybertronlabs.us" ]  # Replace with domain names that the proxy is allowed to redirect to after auth, prepend . for wildcards, i.e. ".example.com"
    whitelist_domains = [ "cybertronlabs.us" ]  # Same as above
    reverse_proxy = true
    ssl_insecure_skip_verify = true
    upstreams = ["static://200"]
    pass_access_token = true
    redirect_url = "https://homepage.cybertronlabs.us/oauth2/callback"
