---
apiVersion: v1
kind: Secret
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
type: Opaque
data:
  HOMEPAGE_VAR_SONARR_API: b1a685a88922469ebba5624d5f8921c4
  HOMEPAGE_VAR_RADARR_API: 0db6f88283834cfe97d294369f212038
  HOMEPAGE_VAR_LIDARR_API: 0ffa1e584a3c452e8d81482240613c91
  HOMEPAGE_VAR_PIHOLE_PASS: N0G5@p3t0da4
  HOMEPAGE_VAR_SAB_API: cc7128b727b94d47b74d3fccfec82421
  HOMEPAGE_VAR_PLEX_API: ntwAcmJp3H1Qxd6k4hVs
  HOMEPAGE_VAR_JELLYFIN_API: 4e717fceb3ed4fa7afe319a491aa702e
  HOMEPAGE_VAR_JELLYFIN2_API: 3d31919885544c89a860e902cb806773
  HOMEPAGE_VAR_GITEA_API: d0f6dd0a160fdc27df9c7423beb1f69c404b965c
  HOMEPAGE_VAR_TRUENAS_API: 1-PEITyTdU9zmE17NBhGhNAg6O91ThWEDMmTp8RCfmn16ZTwxi13EfLTfi70ApVUYJ
  HOMEPAGE_VAR_AUTH_API: XepbvTFPc7yMfe5J2x4SfEVxkEfAGxKTTFqjdKoZDiAa8T2ooCrnBG7roSQw
  HOMEPAGE_VAR_IMMICH_API: 4U10Mt6pLQ0gtjyifnSwQ8D9agOTqE6oq9SFdIGT9s
  HOMEPAGE_VAR_NC_API: c5f5c3b4-62be-4959-8793-9e178b9f69fc
  HOMEPAGE_VAR_GRAFANA_USER: admin
  HOMEPAGE_VAR_GRAFANA_PASS: HTqJ2sZdT*sTMmv2$@ntz%MWU
  HOMEPAGE_VAR_PORTAINER_API: ptr_169wLsxWeRT0lKHjNQ+omLtolA9sFLTgcpxMMso5Ug8=
  HOMEPAGE_VAR_PROMETHEUS_API: 9565e575-f297-4b88-9b44-33006abffcdc
  HOMEPAGE_VAR_NC_USER: frank
