apiVersion: v1
kind: Pod
metadata:
  name: debug-jellyfin-log
  namespace: kube-system
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sleep", "1h"]
      volumeMounts:
        - name: jellyfin-logs
          mountPath: /jellyfin/config
  volumes:
    - name: jellyfin-logs
      hostPath:
        path: /var/lib/kubelet/pods/99771b08-5367-4bb7-8d16-95f5f2149816/volumes/kubernetes.io~csi/jellyfin/mount/config/log
        type: Directory
  restartPolicy: Never
