[Definition]
actionstart =
actionstop =
actioncheck =
actionban = curl -s -X POST "https://gotify.cybertronlabs.us/message" \
    -H "X-Gotify-Key: ATku--qu5nx3VP6" \
    -F "title=Fail2Ban Alert" \
    -F "message=<name>: Banned <ip> for too many failed attempts" \
    -F "priority=5"
actionunban =

