[Definition]
failregex = ^.*Authentication request for .* has been denied \(IP: "<ADDR>"\)\.
#failregex = ^\[[^\]]+\] \[INF\] \[\d+\] Jellyfin\.Server\.Implementations\.Users\.UserManager: Authentication request for ".*" has been denied \(IP: "<HOST>"\)\.
ignoreregex =

