apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: codeserver
    app.kubernetes.io/instance: codeserver
    app.kubernetes.io/name: codeserver
  name: codeserver
  namespace: codeserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "codeserver"
        vault.hashicorp.com/agent-inject-secret-env: "kv-v2/data/codeserver/secret"
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "kv-v2/data/codeserver/secret" -}}
          bind-addr: 0.0.0.0:8080
          auth: password
          password: {{ .Data.data.PASSWORD }}
          cert: false
          {{- end }}
        vault.hashicorp.com/agent-inject-file-env: "config.yaml"
      labels:
        app: codeserver
    spec:
      serviceAccountName: csa1
      nodeSelector:
        worker: "true"
      containers:
        - name: codeserver
          image: codercom/code-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: https
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /home/coder/.config/code-server
              cp /vault/secrets/config.yaml /home/coder/.config/code-server/config.yaml
              exec /usr/bin/code-server
          env:
            - name: TZ
              value: "America/Chicago"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: codeserver
              mountPath: /home/coder
      volumes:
        - name: codeserver
          persistentVolumeClaim:
            claimName: codeserver

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csa1
  namespace: codeserver
secrets:
  - name: csa1-token

---
apiVersion: v1
kind: Secret
metadata:
  name: csa1-token
  namespace: codeserver
  annotations:
    kubernetes.io/service-account.name: csa1
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: Service
metadata:
  name: codeserver
  namespace: codeserver
spec:
  selector:
    app: codeserver
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: codeserver
  namespace: codeserver
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.cs.cybertronlabs.us`)
      kind: Rule
      services:
        - name: codeserver
          port: 8080
    - match: Host(`cs.cybertronlabs.us`)
      kind: Rule
      services:
        - name: codeserver
          port: 8080
      middlewares:
        - name: default-headers
          namespace: traefik
        - name: rate-limit
          namespace: traefik
        - name: authentik-outpost
          namespace: traefik
#  tls:
#    secretName: cybertronlabs-tls # change to your cert name

