apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret-secret
  namespace: codeserver
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: codeserver/secret
  refreshAfter: 10s
  rolloutRestartTargets:
    - kind: Deployment
      name: codeserver
  destination:
    create: true
    name: secret
