apiVersion: v1
kind: ServiceAccount
metadata:
  name: csa1
  namespace: codeserver
secrets:
  - name: csa1-token

---
apiVersion: v1
kind: Secret
metadata:
  name: csa1-token
  namespace: codeserver
  annotations:
    kubernetes.io/service-account.name: csa1
type: kubernetes.io/service-account-token
