apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: codeserver
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: codeserver
    serviceAccount: default
    audiences:
      - https://kubernetes.default.svc
