apiVersion: v1
kind: Namespace
metadata:
  name: media
---
# SMB PersistentVolumes
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-arr-media
spec:
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: arr-media
    volumeAttributes:
      source: "//192.168.40.4/media" # Change this to your SMB IP and share name
    nodeStageSecretRef:
      name: smbcreds
      namespace: default

---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-arr-temp
spec:
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: arr-temp
    volumeAttributes:
      source: "//192.168.40.4/temp" # Change this to your SMB IP and share name
    nodeStageSecretRef:
      name: smbcreds
      namespace: default

---
# SMB PVCs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-arr-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10000Gi
  volumeName: pv-arr-media
  storageClassName: smb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-arr-temp
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10000Gi
  volumeName: pv-arr-temp
  storageClassName: smb

---
# ConfigMap for shared env
apiVersion: v1
kind: ConfigMap
metadata:
  name: media-env
  namespace: media
data:
  TZ: America/Chicago
  PUID: "1000"
  PGID: "1000"
