# -- Sonarr --
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      nodeSelector:
        worker: "true"
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          ports:
            - containerPort: 8989
          envFrom:
            - configMapRef:
                name: media-env
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: smb-temp
            - mountPath: /tv
              name: smb-media
          readinessProbe:
            httpGet:
              path: /
              port: 8989
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 8989
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: pv-arr-temp
          persistentVolumeClaim:
            claimName: pv-arr-temp
        - name: pv-arr-media
          persistentVolumeClaim:
            claimName: pv-arr-media
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
spec:
  selector:
    app: sonarr
  ports:
    - port: 8989
      targetPort: 8989
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: media
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.sonarr.cybertronlabs.us`) # change to your domain
      kind: Rule
      services:
        - name: sonarr
          port: 8989
    - match: Host(`sonarr.cybertronlabs.us`) # change to your domain
      kind: Rule
      services:
        - name: sonarr
          port: 8989
      middlewares:
        - name: bouncer
          namespace: traefik
        - name: default-headers
          namespace: traefik
        - name: rate-limit
          namespace: traefik
#  tls:
#    secretName: cybertronlabs-tls # change to your cert name

