# for raw logs format: json or cri (docker|containerd)
container_runtime: containerd
agent:
  # Specify each pod whose logs you want to process
  acquisition:
    # The namespace where the pod is located
    - namespace: traefik
      # The pod name
      podName: traefik-*
      # as in crowdsec configuration, we need to specify the program name to find a matching parser
      program: traefik
  env:
    - name: COLLECTIONS
      value: "crowdsecurity/traefik"
    - name: DISABLE_PARSERS
      value: "crowdsecurity/whitelists"
  nodeSelector:
    worker: "true"
lapi:
  env:
    # To enroll the Security Engine to the console
    - name: DISABLE_ONLINE_API
      value: "true"
  #    - name: ENROLL_KEY
  #      value: "cm9eldz8t000f10jc5oz8xg9w"
  #    - name: ENROLL_INSTANCE_NAME
  #      value: "my-k3s-cluster"
  #    - name: ENROLL_TAGS
  #      value: "k3s linux test"
  nodeSelector:
    worker: "true"
