---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich-smb
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20000Gi
  volumeName: pv-immich-smb
  storageClassName: smb
