---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-smb
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10000Gi
  volumeName: pv-jellyfin-smb
  storageClassName: smb
