---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nextcloud-smb
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10000Gi
  volumeName: pv-nextcloud-smb
  storageClassName: smb
