apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: exportarr-secret
  namespace: monitoring
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: exportarr/secret
  refreshAfter: 10s
  rolloutRestartTargets:
    - kind: Deployment
      name: exportarr
  destination:
    create: true
    name: exportarr-secret
